//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.4.4
//     from Assets/_Source/Input/MainActions.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

namespace Input
{
    public partial class @MainActions : IInputActionCollection2, IDisposable
    {
        public InputActionAsset asset { get; }
        public @MainActions()
        {
            asset = InputActionAsset.FromJson(@"{
    ""name"": ""MainActions"",
    ""maps"": [
        {
            ""name"": ""MouseMap"",
            ""id"": ""a891e03a-3931-4661-8c38-52fc6e3f7433"",
            ""actions"": [
                {
                    ""name"": ""Drag"",
                    ""type"": ""Value"",
                    ""id"": ""49aa076b-84c3-41e9-a52e-7434b64b2bf4"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Click"",
                    ""type"": ""Button"",
                    ""id"": ""67ff7df5-43a5-4ea6-866f-d17e2455e4ff"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""49a4082c-fcee-4b96-9e81-82605c353345"",
                    ""path"": ""<Mouse>/position"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Drag"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""3d38e8a4-9b54-4847-85a6-b3a9eb27a45c"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Click"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
            // MouseMap
            m_MouseMap = asset.FindActionMap("MouseMap", throwIfNotFound: true);
            m_MouseMap_Drag = m_MouseMap.FindAction("Drag", throwIfNotFound: true);
            m_MouseMap_Click = m_MouseMap.FindAction("Click", throwIfNotFound: true);
        }

        public void Dispose()
        {
            UnityEngine.Object.Destroy(asset);
        }

        public InputBinding? bindingMask
        {
            get => asset.bindingMask;
            set => asset.bindingMask = value;
        }

        public ReadOnlyArray<InputDevice>? devices
        {
            get => asset.devices;
            set => asset.devices = value;
        }

        public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

        public bool Contains(InputAction action)
        {
            return asset.Contains(action);
        }

        public IEnumerator<InputAction> GetEnumerator()
        {
            return asset.GetEnumerator();
        }

        IEnumerator IEnumerable.GetEnumerator()
        {
            return GetEnumerator();
        }

        public void Enable()
        {
            asset.Enable();
        }

        public void Disable()
        {
            asset.Disable();
        }
        public IEnumerable<InputBinding> bindings => asset.bindings;

        public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
        {
            return asset.FindAction(actionNameOrId, throwIfNotFound);
        }
        public int FindBinding(InputBinding bindingMask, out InputAction action)
        {
            return asset.FindBinding(bindingMask, out action);
        }

        // MouseMap
        private readonly InputActionMap m_MouseMap;
        private IMouseMapActions m_MouseMapActionsCallbackInterface;
        private readonly InputAction m_MouseMap_Drag;
        private readonly InputAction m_MouseMap_Click;
        public struct MouseMapActions
        {
            private @MainActions m_Wrapper;
            public MouseMapActions(@MainActions wrapper) { m_Wrapper = wrapper; }
            public InputAction @Drag => m_Wrapper.m_MouseMap_Drag;
            public InputAction @Click => m_Wrapper.m_MouseMap_Click;
            public InputActionMap Get() { return m_Wrapper.m_MouseMap; }
            public void Enable() { Get().Enable(); }
            public void Disable() { Get().Disable(); }
            public bool enabled => Get().enabled;
            public static implicit operator InputActionMap(MouseMapActions set) { return set.Get(); }
            public void SetCallbacks(IMouseMapActions instance)
            {
                if (m_Wrapper.m_MouseMapActionsCallbackInterface != null)
                {
                    @Drag.started -= m_Wrapper.m_MouseMapActionsCallbackInterface.OnDrag;
                    @Drag.performed -= m_Wrapper.m_MouseMapActionsCallbackInterface.OnDrag;
                    @Drag.canceled -= m_Wrapper.m_MouseMapActionsCallbackInterface.OnDrag;
                    @Click.started -= m_Wrapper.m_MouseMapActionsCallbackInterface.OnClick;
                    @Click.performed -= m_Wrapper.m_MouseMapActionsCallbackInterface.OnClick;
                    @Click.canceled -= m_Wrapper.m_MouseMapActionsCallbackInterface.OnClick;
                }
                m_Wrapper.m_MouseMapActionsCallbackInterface = instance;
                if (instance != null)
                {
                    @Drag.started += instance.OnDrag;
                    @Drag.performed += instance.OnDrag;
                    @Drag.canceled += instance.OnDrag;
                    @Click.started += instance.OnClick;
                    @Click.performed += instance.OnClick;
                    @Click.canceled += instance.OnClick;
                }
            }
        }
        public MouseMapActions @MouseMap => new MouseMapActions(this);
        public interface IMouseMapActions
        {
            void OnDrag(InputAction.CallbackContext context);
            void OnClick(InputAction.CallbackContext context);
        }
    }
}
